version: 0.1

phases:
  pre_build:
    commands:
      - sbt clean
  build:
    commands:
      - echo Build started on `date`
      - echo Run the test and package the code...
      - sbt compile
      - sbt assembly
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir deploy
      - mkdir deploy/lib
      - cp target/scala-2.11/api.jar deploy/lib
      - aws cloudformation package --template-file sam.yml --s3-bucket lambda.github.api --output-template-file new-sam.yml
artifacts:
  type: zip
  files:
    - deploy/lib/api.jar
    - new-sam.yml