AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  lambdaGithubRepositories:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'repository.Handler::handleRequest'
      Runtime: java8
      CodeUri: ./deploy
      MemorySize: 512
      Timeout: 10
      Policies: AWSLambdaBasicExecutionRole
      Events:
        MyProviderApi:
          Type: Api
          Properties:
            Path: /api/v1/repositories/{username}
            Method: get
      Environment:
        Variables:
          githubApiUrl: https://api.github.com
          personalAccessToken: yourEncryptedToken